spring:
  application:
    name: order-service

#data source
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: sanu1234
    url: jdbc:mysql://localhost:3306/OrderManage?createDatabaseIfNotExist=true

#Jpa
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    generate-ddl: true

#config server client
#  config:
#    import: optional:configserver:http://localhost:8085/

server:
  port: 8083

info:
  app:
    name: ${spring.application.name}

#for eureka client
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

#for actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
